### ISSUE TITLE
Create LICENSE

### ISSUE THREAD

**Issue by mehdichaouch** [strainel/elysee2022#1]
Hello Stéphane :wave: ,

I liked your repo, thanks for writing it.

Did you think about adding a LICENSE like the [MIT license](https://github.com/git/git-scm.com/blob/main/MIT-LICENSE.txt), to allow contributor to work/fork your this repo?

Merci :wink:

**Comment by strainel** [comment]
Hey Mehdi 
Thanks for your message. I juste add a AGPL licence to the repo. 
have a nice day 🌞
